const env = import.meta.env;

const {
    VITE_API_URL: API_URL,
    VITE_PAGE_TITLE: PAGE_TITLE,
    VITE_DESCRIPTION: META_DESCRIPTION,
    VITE_RECAPTCHA_KEY: RECAPTCHA_KEY,
} = env;

export { API_URL, PAGE_TITLE, META_DESCRIPTION, RECAPTCHA_KEY };
